MeB takeover
metabrainz/design-system pull request #39
Opened 2021-09-22 16:44 UTC by akshaaatt

- Migrate the design-system to be compatible for all MeB projects.

2021-09-22 19:25 UTC, mwiencek requested changes

2021-09-22 19:25 UTC, mwiencek commented on dist/bootstrap.css
> + * all Bootstrapified shared must have a .bs class on their containing
This change seems wrong

2021-09-22 19:25 UTC, mwiencek commented on scss/bootstrap-prod.scss
> + * all Bootstrapified shared must have a .bs class on their containing
Same here

2021-09-23 02:31 UTC, y-young commented
What about putting shared (common) components under `components` and making multiple folders for exclusive components of projects? e.g: `components/mb`, `components/lb`.

2021-09-23 04:29 UTC, akshaaatt commented on dist/bootstrap.css
> + * all Bootstrapified shared must have a .bs class on their containing
Thanks for pointing this out!

2021-09-23 04:29 UTC, akshaaatt commented on scss/bootstrap-prod.scss
> + * all Bootstrapified shared must have a .bs class on their containing
Thank you!

2021-09-23 04:38 UTC, akshaaatt commented
> What about putting shared (common) components under `components` and making multiple folders for exclusive components of projects? e.g: `components/mb`, `components/lb`.

@y-young Thanks for the thought. I was going to name them as `common` but went with `shared` so that the hierarchy can be maintained and common doesn't nudge up and confuse us. Shared will be down in the folder and easy to access for the developers who work on this in the future. 
Moving shared under components would work but then they would be handled separately. Currently they can be in the same folder. If these are necessary issues and could be really fruitful to update, we can consider doing so.

2022-01-22 22:01 UTC, merged